Added Home-Assistant autodiscovery MQTT
eode/ClassicMQTT pull request #2
Opened 2024-01-18 07:17 UTC by FastFrank

Hello,

i added some code for HA autodiscovery so the Classic shows up as a MQTT device.
It also sends different icons for the chargestate and SOC.

![image](https://github.com/eode/ClassicMQTT/assets/20457556/acd6c255-6cc6-4b81-ad85-ea725d3445dd)

Do you (eode) use HA?

Greetings!
(and thank you for fixing the python 3 stuff)

2024-01-24 15:21 UTC, eode requested changes
Thanks for your changes!  After review issues are addressed I'll do a PR upstream.

Yes, I use HA myself -- currently, I'm doing some of this info in HA templates (like the charge state text), but I think it's a decent idea to move it into MQTT.

2024-01-24 15:21 UTC, eode commented on code/Python/classic_mqtt.py
> +    'mqttPort':os.getenv('MQTT_PORT', "18883"), \
These appear to be local preference changes.  If they have relevance outside of that, let me know, otherwise, please remove from the PR.

If they do have relevance outside of adding HA Autodiscovery, please make them a separate PR.

2024-01-24 15:21 UTC, eode commented on code/Python/classic_mqtt.py
> +modeAwake                   = True
Local preference?

2024-01-24 15:21 UTC, eode commented on code/Python/support/classic_jsonencoder.py
> +            classicData["deviceName"] = classicData["deviceName"] + chr(x)   # "{:02X}".format(x) #+ chr(x)
If I'm reading this correctly, an undesired 0 is included at the beginning or end (probably the end) of uint_array, and you want to get rid of it, yes?

If so, how about:
`classicData["deviceName"] = "".join(chr(x) for x in uint_array).strip(chr(0))`

Also, needs comment cleanup

2024-01-24 15:21 UTC, eode commented on code/Python/support/classic_jsonencoder.py
> +    classicData["buildDate"] = "{}-{}-{}".format(decoded["Year"],decoded["Month"],decoded["Day"])
Is this necessary for HA integration?  If not, move to a separate PR.

2024-01-24 15:21 UTC, eode commented on code/Python/support/classic_jsonencoder.py
> +    #return "{:04n}-{:02n}-{:02n} {:02n}:{:02n}:{:02n} dow:{} doy:{} {:08x}".format(tyear,tmnth,tdyom,thour,tmins,tsecs,tdyow,tdyoy,CTIME2)
cleanup

2024-01-24 15:21 UTC, eode commented on code/Python/support/classic_modbusdecoder.py
> +#from pymodbus.compat import iteritems
cleanup

2024-01-24 15:21 UTC, eode commented on code/Python/support/classic_modbusdecoder.py
> +
remove whitespace

2024-01-24 19:23 UTC, FastFrank commented on code/Python/classic_mqtt.py
> +    'mqttPort':os.getenv('MQTT_PORT', "18883"), \
I'm sorry... i will change it back

2024-01-24 19:23 UTC, FastFrank commented on code/Python/classic_mqtt.py
> +modeAwake                   = True
same

2024-01-24 19:25 UTC, FastFrank commented on code/Python/support/classic_jsonencoder.py
> +            classicData["deviceName"] = classicData["deviceName"] + chr(x)   # "{:02X}".format(x) #+ chr(x)
In the https://www.midnitesolar.com/firmware/classic_register_map_Rev-C5-December-8-2013.pdf it says:

`End with 0 if less than 8 chars`

2024-01-24 19:31 UTC, FastFrank commented on code/Python/support/classic_jsonencoder.py
> +    #return "{:04n}-{:02n}-{:02n} {:02n}:{:02n}:{:02n} dow:{} doy:{} {:08x}".format(tyear,tmnth,tdyom,thour,tmins,tsecs,tdyow,tdyoy,CTIME2)
I was busy with the "Day of week"  and  "Day of year" that should reside in CTIME2.
But some how it does not work...

2024-01-24 20:02 UTC, eode commented on code/Python/classic_mqtt.py
> +    'mqttPort':os.getenv('MQTT_PORT', "18883"), \
No need to apologize :-)

Thanks for fixing it, though.

2024-01-24 20:08 UTC, eode commented on code/Python/support/classic_jsonencoder.py
> +            classicData["deviceName"] = classicData["deviceName"] + chr(x)   # "{:02X}".format(x) #+ chr(x)
Ok, then adding `.rstrip(chr(0))` to the original line should do the trick, as in:

`classicData["deviceName"] = "".join(chr(x) for x in uint_array).rstrip(chr(0))`

Good catch, though.

2024-01-24 20:59 UTC, eode commented on code/Python/support/classic_jsonencoder.py
> +    #return "{:04n}-{:02n}-{:02n} {:02n}:{:02n}:{:02n} dow:{} doy:{} {:08x}".format(tyear,tmnth,tdyom,thour,tmins,tsecs,tdyow,tdyoy,CTIME2)
I'm not sure knowing what time the Classic thinks it is is super-important.  I mean, I would accept a PR with that resolved, but I don't think it's necessary for this PR.

That said, the organization of this segment is pretty quirky -- what's in the decoded `CTIME0, CTIME1, CTIME2` is arguably not decoded correctly, but that depends on a lot of interpretation:

``` python
# *** i think ***
v4214 = decoded['CTIME0'] >> 16  # value in the 4214 register
v4215 = decoded['CTIME0'] 0xffff  # value in the 4215 register
CTIME0 = v4215 << 16 + v4214

v4216 = decoded['CTIME1'] >> 16 # value in the 4216 register
v4217 = decoded['CTIME1'] << 16 # value in the 4217 register
CTIME1 = v4217 << 16 + v4216

CTIME2 = decoded['CTIME2'] >> 16 # value in the 4218 register
```

I *think* that the swap there is the proper way to decode that register -- at which point you can extract the table information you're trying to extract.

Buuut, again, that can go in another PR.  If you want a timestamp now, just do a unix timestamp or something based on that, as the platform running ClassicMQTT probably has more accurate time, anyways.

2024-01-26 08:06 UTC, FastFrank commented on code/Python/support/classic_jsonencoder.py
> +    #return "{:04n}-{:02n}-{:02n} {:02n}:{:02n}:{:02n} dow:{} doy:{} {:08x}".format(tyear,tmnth,tdyom,thour,tmins,tsecs,tdyow,tdyoy,CTIME2)
It contains the current time that is in the Classic device. 
In the register map it shows which bits are used for the date parts:
![image](https://github.com/eode/ClassicMQTT/assets/20457556/cad74fed-fa68-401e-ae9f-f5c65ffda413)
There is a typo with BITS 36:24 ... it has to be 26:24 in 4214-1.
And for the Day of Week in 4218-1 i wonder why use 12 bits when 9 bits is enough to contain the 366 value.
So if you only want the value of bits 26:24 ... the mask is 0x07000000 and shift it 24 bits to the right...
![image](https://github.com/eode/ClassicMQTT/assets/20457556/8616430a-bf5f-470e-a9e5-6b096085ed01)

![image](https://github.com/eode/ClassicMQTT/assets/20457556/5f9bbfc5-147f-4a1d-a239-f4deb57bfc68)

2024-01-26 15:48 UTC, eode commented on code/Python/support/classic_jsonencoder.py
> +    #return "{:04n}-{:02n}-{:02n} {:02n}:{:02n}:{:02n} dow:{} doy:{} {:08x}".format(tyear,tmnth,tdyom,thour,tmins,tsecs,tdyow,tdyoy,CTIME2)
![Screenshot from 2024-01-26 10-38-21](https://github.com/eode/ClassicMQTT/assets/2475983/2b902a94-faff-4f4f-9d4c-f42264ab94eb)

So, this is what I was referring to -- I think it's what's needed to set up the base structure referenced by the table.

So, if I'm reading that right, then in order to get the bit structure referenced by `4214-1`, You actually need to read `4214` and `4215`, then swap them so the result is `<16 bits -- 4215><16 bits -- 4214>`.

*then* you can access the bytes as specified in `4214-1` and `4216-1` (`4218` is just a single 16-bit read or a 32-bit read and a bitshift >> 16, so using that one is easier)

2024-01-26 15:50 UTC, eode commented
Sweet.  Overall, it looks good enough at this point.  But, I would like to lock these changes behind a CLI flag, like `--homeassistant`.

After that, I'm ok with it as-is.

2024-01-26 19:28 UTC, FastFrank commented on code/Python/support/classic_jsonencoder.py
> +    #return "{:04n}-{:02n}-{:02n} {:02n}:{:02n}:{:02n} dow:{} doy:{} {:08x}".format(tyear,tmnth,tdyom,thour,tmins,tsecs,tdyow,tdyoy,CTIME2)
[4214] is a WORD aka 2 bytes ... and the Classic is doing:  ([4215] << 16) + [4214] so decoder.decode_32bit_uint() will get the 2 WORDS / 4 BYTES / 32 bits in the right order... and (almost) the same time shows up in HA like in the MidNite Solar Status Panel:
( i can not open them at the same time... )

![image](https://github.com/eode/ClassicMQTT/assets/20457556/495dbdd3-b7cf-4d30-83ec-5b4883c8f678)

![image](https://github.com/eode/ClassicMQTT/assets/20457556/df1509ca-4acd-444b-9ec6-0f1407995f16)

my Classic is ahead about 20 minutes...

2024-01-27 02:04 UTC, eode commented
I can merge this now -- thanks for all of your work on it!

I do still have some small areas of contention, but you might have your reasons for them -- For example, I think the SOC should perhaps be HA's `device_class` `battery`, and its icon should then automatically reflect the state..  ..but if we want to refine that, we can do it in another PR.

Thanks for your contribution!

2024-01-27 02:05 UTC, merged

2024-01-27 10:48 UTC, FastFrank commented
> I can merge this now -- thanks for all of your work on it!
> 
> I do still have some small areas of contention, but you might have your reasons for them -- For example, I think the SOC should perhaps be HA's `device_class` `battery`, and its icon should then automatically reflect the state.. ..but if we want to refine that, we can do it in another PR.
> 
> Thanks for your contribution!

I am glad i can contribute... 
I did not know that HA has a battery device_class... i am trying it now...
But... i did make it the way that if the Charge State is Charging the icon contains the lightning symbol and if the classic is not charging is does not contain the lightning symbol.

Maybe one day we can reach the point that it is possible to write to the register to change the settings of the Classic.

Thanks!

2024-01-27 10:50 UTC, FastFrank commented
It turned green on the graph thing...

![image](https://github.com/eode/ClassicMQTT/assets/20457556/7775fe72-f1c0-4b53-b01a-88145e4f31a2)